# Generated by Django 2.1.2 on 2024-03-29 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('company_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='app.Organization')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_on'],
            },
        ),
    ]
