# Generated by Django 2.1.2 on 2024-03-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='company_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customers',
            name='display_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
